In [ ]:
#Program untuk menggunakan model


In [ ]:
from google.colab import drive
drive.mount('/content/drive')


Mounted at /content/drive


<h1>Skin Type Model</h1>

In [ ]:
path = "./drive/My Drive/Model-ML/skin-type-model-80.h5"

In [5]:
import keras
from keras.models import load_model
from keras.preprocessing import image

In [6]:
print(keras.__version__)

2.8.0


In [ ]:
model = load_model(path)

In [ ]:
import numpy as np
from google.colab import files


uploaded = files.upload()

for fn in uploaded.keys():
 
  # predicting images
  path = fn
  img = image.load_img(path, target_size=(150, 150))
  x = image.img_to_array(img)
  x = np.expand_dims(x, axis=0)

  images = np.vstack([x])
  classes = model.predict(images, batch_size=10)
  print(fn)
  print(classes)

KeyboardInterrupt: ignored

<h1>Skin Disease</h1>

In [ ]:
path = "/content/drive/MyDrive/Copy of skin-disease-model-72.h5"

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
from keras.models import load_model

In [ ]:
model = load_model(path)

In [ ]:
import numpy as np
from google.colab import files
from keras.preprocessing import image

uploaded = files.upload()

for fn in uploaded.keys():
 
  # predicting images
  path = fn
  img = image.load_img(path, target_size=(150, 150))
  x = image.img_to_array(img)
  x = np.expand_dims(x, axis=0)

  images = np.vstack([x])
  classes = model.predict(images, batch_size=10)
  print(fn)
  print(classes)

Saving 1.jpg to 1.jpg
Saving 2.jpg to 2.jpg
Saving 3.jpg to 3.jpg
Saving 4.jpg to 4.jpg
Saving 5.jpg to 5.jpg
Saving 6.jpg to 6.jpg
Saving 7.jpg to 7.jpg
1.jpg
[[0.0000000e+00 0.0000000e+00 1.0000000e+00 2.0591485e-10]]
2.jpg
[[0.0000000e+00 0.0000000e+00 1.0000000e+00 2.7607818e-31]]
3.jpg
[[0.0000000e+00 0.0000000e+00 1.0000000e+00 5.9464534e-15]]
4.jpg
[[0.000000e+00 0.000000e+00 1.000000e+00 2.333379e-36]]
5.jpg
[[0. 0. 1. 0.]]
6.jpg
[[0.000000e+00 0.000000e+00 1.000000e+00 2.765086e-13]]
7.jpg
[[0. 0. 1. 0.]]


<h1>Python to JSON</h1>

In [ ]:
! python /content/drive/MyDrive/Program-ML/model_reader.py type "/content/drive/MyDrive/Data-ML/Skin Disease Detection/after_cleaning/Acne/1.jpg"

/content/drive/MyDrive/Model-ML/Model Final/skin-type-model-80.h5 /content/drive/MyDrive/Data-ML/Skin Disease Detection/after_cleaning/Acne/1.jpg
2022-05-30 14:59:32.378992: E tensorflow/stream_executor/cuda/cuda_driver.cc:271] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
[6.3943756e-01 2.1617074e-05 3.5737586e-01 3.1649533e-03]
0.63943756

